import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'
import type { ExportData } from './exportReport'

function vendorName(data: ExportData, vendorId: string): string {
  return data.vendors.find((v) => v.id === vendorId)?.name ?? vendorId
}

function avgScore(data: ExportData, vendorId: string, criteriaId: string): number {
  const scorerIds = Object.keys(data.scorerScores)
  if (scorerIds.length === 0) return 0
  const total = scorerIds.reduce((sum, sid) => {
    const vendorMap = data.scorerScores[sid] ?? {}
    const criteriaMap = vendorMap[vendorId] ?? {}
    return sum + (criteriaMap[criteriaId] ?? 0)
  }, 0)
  return total / scorerIds.length
}

function buildReportHTML(data: ExportData): string {
  const sorted = data.finalScores.slice().sort((a, b) => b.final_score - a.final_score)
  const scorerCount = Object.keys(data.scorerScores).length

  const summaryRows = sorted
    .map((fs, i) => `
      <tr style="background:${i === 0 ? '#f0fdf4' : i % 2 === 0 ? '#f9fafb' : '#fff'}">
        <td style="padding:8px 12px;font-weight:${i === 0 ? 'bold' : 'normal'};color:${i === 0 ? '#166534' : '#111'}">
          ${String(i + 1)}${i === 0 ? ' 🏆' : ''}
        </td>
        <td style="padding:8px 12px;font-weight:${i === 0 ? 'bold' : 'normal'}">
          ${vendorName(data, fs.vendor_id)}
        </td>
        <td style="padding:8px 12px;text-align:right;font-weight:bold;font-size:16px;color:${i === 0 ? '#166534' : '#111'}">
          ${fs.final_score.toFixed(2)}
        </td>
        <td style="padding:8px 12px;text-align:center;color:#6b7280">${String(fs.scorer_count)}</td>
      </tr>`)
    .join('')

  const criteriaRows = data.criteria
    .map((c, idx) => `
      <tr style="background:${idx % 2 === 0 ? '#f9fafb' : '#fff'}">
        <td style="padding:7px 12px">${c.name}</td>
        <td style="padding:7px 12px;text-align:center">${String(c.weight)}%</td>
        ${data.vendors.map((v) => `<td style="padding:7px 12px;text-align:center">${avgScore(data, v.id, c.id).toFixed(1)}</td>`).join('')}
      </tr>`)
    .join('')

  const totalRow = `
    <tr style="background:#eff6ff;font-weight:bold">
      <td style="padding:8px 12px">Weighted Total</td>
      <td style="padding:8px 12px;text-align:center">100%</td>
      ${data.vendors.map((v) => {
        const ws = data.criteria.reduce((sum, c) => sum + (avgScore(data, v.id, c.id) * c.weight) / 100, 0)
        return `<td style="padding:8px 12px;text-align:center;color:#1d4ed8">${ws.toFixed(2)}</td>`
      }).join('')}
    </tr>`

  const vendorHeaders = data.vendors
    .map((v) => `<th style="padding:8px 12px;background:#374151;color:#fff;text-align:center;min-width:100px">${v.name}</th>`)
    .join('')

  return `
    <div style="font-family:'Sarabun','Noto Sans Thai',Arial,sans-serif;font-size:13px;color:#111;background:#fff;padding:32px;width:720px">
      <h1 style="font-size:22px;font-weight:bold;margin:0 0 8px 0">Vendor Selection Scoring Report</h1>
      <p style="margin:4px 0;color:#4b5563">Project: <strong>${data.requestTitle}</strong></p>
      <p style="margin:4px 0 24px 0;color:#4b5563">Export Date: ${data.exportDate} &nbsp;|&nbsp; Scorers: ${String(scorerCount)} คน</p>

      <h2 style="font-size:15px;font-weight:bold;margin:0 0 8px 0;border-bottom:2px solid #2563eb;padding-bottom:4px">Scoring Summary</h2>
      <table style="width:100%;border-collapse:collapse;margin-bottom:28px;border:1px solid #e5e7eb">
        <thead>
          <tr style="background:#2563eb;color:#fff">
            <th style="padding:8px 12px;text-align:left">Rank</th>
            <th style="padding:8px 12px;text-align:left">Vendor</th>
            <th style="padding:8px 12px;text-align:right">Final Score</th>
            <th style="padding:8px 12px;text-align:center">Scorers</th>
          </tr>
        </thead>
        <tbody>${summaryRows}</tbody>
      </table>

      <h2 style="font-size:15px;font-weight:bold;margin:0 0 8px 0;border-bottom:2px solid #374151;padding-bottom:4px">Criteria & Average Scores</h2>
      <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb">
        <thead>
          <tr>
            <th style="padding:8px 12px;background:#374151;color:#fff;text-align:left">Criteria</th>
            <th style="padding:8px 12px;background:#374151;color:#fff;text-align:center">Weight</th>
            ${vendorHeaders}
          </tr>
        </thead>
        <tbody>${criteriaRows}${totalRow}</tbody>
      </table>

      <p style="margin-top:24px;font-size:11px;color:#9ca3af;text-align:right">
        Generated by Vendor Selection System — DoHome IT
      </p>
    </div>`
}

export async function exportPDFWithHTML(data: ExportData): Promise<void> {
  // Create hidden container
  const container = document.createElement('div')
  container.style.cssText = 'position:fixed;left:-9999px;top:0;z-index:-1'
  container.innerHTML = buildReportHTML(data)
  document.body.appendChild(container)

  // Add Google Fonts for Thai support
  const style = document.createElement('style')
  style.textContent = `@import url('https://fonts.googleapis.com/css2?family=Sarabun:wght@400;700&display=swap');`
  document.head.appendChild(style)

  // Wait for fonts to load
  await document.fonts.ready

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
      logging: false,
    })

    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

    const pageW = pdf.internal.pageSize.getWidth()
    const pageH = pdf.internal.pageSize.getHeight()
    const margin = 10
    const imgW = pageW - margin * 2
    const imgH = (canvas.height * imgW) / canvas.width

    let y = margin
    let heightLeft = imgH

    pdf.addImage(imgData, 'PNG', margin, y, imgW, imgH)
    heightLeft -= pageH - margin * 2

    while (heightLeft > 0) {
      y = heightLeft - imgH + margin
      pdf.addPage()
      pdf.addImage(imgData, 'PNG', margin, y, imgW, imgH)
      heightLeft -= pageH - margin * 2
    }

    const fileName = `${data.requestTitle.replace(/\s+/g, '-')}-scoring-report-${data.exportDate}.pdf`
    pdf.save(fileName)
  } finally {
    document.body.removeChild(container)
    document.head.removeChild(style)
  }
}
